replicaCount: 1

image:
  repository: nginx-demo
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

env: default
resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

config:
  message: "hello it's me"
